application: skk-dict-mirror
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /testpage
  static_dir: testpage/
  upload:

- url: /extension
  static_dir: extension/

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
